#!/usr/bin/env bash
# Untrack specs/ and .wiggum/ in the ainetops repo and ignore them wholesale.
#
# WHY: .wiggum carries 35,568 tracked files -- 30,559 of them a vendored toolchain
# under features/*/tools, plus build-gnmi sources, gate proofs and run logs. None of
# it is source; it is harness working state, and it drowns the actual platform code.
# specs/ was already ignored, but only the bare `specs/` line -- this makes both
# explicit and complete.
#
# WHY NOT WHILE THE LOOP RUNS: wiggum auto-commits into .wiggum at every gate. A
# `git rm --cached` of 35k paths racing an in-flight `git add` contends on
# .git/index.lock and can fail a phase mid-run. This script refuses to start if an
# orchestrator is live.
set -euo pipefail
REPO=${1:-/root/ainetops-demo}
cd "$REPO"

if pgrep -af "bash /root/wiggum/orchestrator.sh -w $REPO" 2>/dev/null \
     | grep -qv "shell-snapshot\|claude-0\|untrack-specs"; then
  echo "REFUSING: a wiggum orchestrator is still running against $REPO." >&2
  echo "It commits into .wiggum at every gate; untracking 35k paths now can race" >&2
  echo "its index lock and fail a phase. Re-run once the loop has exited." >&2
  exit 3
fi

before=$(git ls-files | wc -l)

# Ignore rules. The pre-existing file already had `specs/` plus a scatter of
# narrow .wiggum/* lines; replace those narrow lines with the whole directory.
python3 - <<'PY'
import re
p = ".gitignore"
s = open(p).read()
# drop the narrow per-file .wiggum rules now subsumed by the directory rule
s = "\n".join(l for l in s.splitlines()
              if not (l.startswith(".wiggum/") and l.strip() != ".wiggum/"))
if not re.search(r"(?m)^\.wiggum/$", s):
    s = s.rstrip("\n") + """

# Wiggum harness working state -- not source. Holds a vendored toolchain
# (features/*/tools, ~30k files), build-gnmi sources, gate evidence, verdicts,
# attempts and run logs. Regenerated by the loop; never needed to build or run
# the platform.
.wiggum/
"""
if not re.search(r"(?m)^\.specify/$", s):
    s = s.rstrip("\n") + "\n.specify/\n"
open(p, "w").write(s)
PY

# Untrack. -r for the tree, --cached so the working files stay on disk (the loop
# still needs them). Quiet: 35k paths of output is noise.
# Each path separately: `git rm` fails the WHOLE invocation if any pathspec
# matches nothing, and `specs/` is already untracked here -- so the combined form
# silently did nothing to .wiggum and reported "removed 0".
for p in specs .wiggum; do
  git ls-files --error-unmatch "$p" >/dev/null 2>&1 || { echo "  (nothing tracked under $p)"; continue; }
  git rm -r --cached --quiet "$p" || echo "  WARNING: git rm failed for $p" >&2
done

after=$(git ls-files | wc -l)
echo "tracked files: $before -> $after  (removed $((before - after)))"
echo
git status --short | head -5
echo "..."
echo "staged deletions: $(git diff --cached --name-only --diff-filter=D | wc -l)"
